FROM quay.io/scylladb/scylla-operator-images:golang-1.24 AS builder
SHELL ["/bin/bash", "-euEo", "pipefail", "-O", "inherit_errexit", "-c"]
WORKDIR /go/src/github.com/pausing-clusters-thesis/proxy-csi-driver
COPY . .
RUN make build --warn-undefined-variables GO_BUILD_PACKAGES=./cmd/proxy-csi-driver

FROM quay.io/scylladb/scylla-operator-images:base-ubuntu-22.04
SHELL ["/bin/bash", "-euEo", "pipefail", "-O", "inherit_errexit", "-c"]

RUN apt-get update && \
    apt-get clean  && \
    rm -rf /var/lib/apt/lists/*

COPY --from=builder /go/src/github.com/pausing-clusters-thesis/proxy-csi-driver/proxy-csi-driver /usr/bin/
ENTRYPOINT ["/usr/bin/proxy-csi-driver"]
