kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: scylladb-local-xfs-immediate
provisioner: local.csi.scylladb.com
volumeBindingMode: Immediate
parameters:
  csi.storage.k8s.io/fstype: xfs