apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gp2-immediate
parameters:
  csi.storage.k8s.io/fstype: xfs
  type: gp2
provisioner: ebs.csi.aws.com
reclaimPolicy: Delete
volumeBindingMode: Immediate