kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: scylladb:proxy-csi-driver-external-provisioner
subjects:
- kind: ServiceAccount
  name: proxy-csi-driver-controller
  namespace: proxy-csi-driver
roleRef:
  kind: ClusterRole
  name: scylladb:proxy-csi-driver-external-provisioner
  apiGroup: rbac.authorization.k8s.io
