kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: scylladb:proxy-csi-driver-volumemanager
subjects:
- kind: ServiceAccount
  name: proxy-csi-driver-node
  namespace: proxy-csi-driver
roleRef:
  kind: ClusterRole
  name: scylladb:proxy-csi-driver-volumemanager
  apiGroup: rbac.authorization.k8s.io
