kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: proxy-csi-driver-node
  namespace: proxy-csi-driver
  labels:
    app.kubernetes.io/name: proxy-csi-driver
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: proxy-csi-driver
  template:
    metadata:
      labels:
        app.kubernetes.io/name: proxy-csi-driver
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      serviceAccountName: proxy-csi-driver-node
      containers:
      - name: proxy-csi-driver-node
        securityContext:
          privileged: true
        image: docker.io/rzetelskik/proxy-csi-driver:latest
        imagePullPolicy: Always
        args:
        - node-server
        - --csi-address=/csi/csi.sock
        - --node-name=$(NODE_NAME)
        - --state-dir=/state
        - --v=4
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        volumeMounts:
        - name: kubelet-dir
          mountPath: /var/lib/kubelet
          mountPropagation: "Bidirectional"
          readOnly: false
        - name: plugin-dir
          mountPath: /csi
          readOnly: false
        - name: state-dir
          mountPath: /state
          readOnly: false
        ports:
        - name: healthz
          containerPort: 9809
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /healthz
            port: healthz
          initialDelaySeconds: 10
          timeoutSeconds: 3
          periodSeconds: 2
          failureThreshold: 5
      - name: csi-driver-registrar
        image: registry.k8s.io/sig-storage/csi-node-driver-registrar@sha256:f25af73ee708ff9c82595ae99493cdef9295bd96953366cddf36305f82555dac
        imagePullPolicy: IfNotPresent
        args:
        - --csi-address=/csi/csi.sock
        - --kubelet-registration-path=/var/lib/kubelet/plugins/proxy.csi.scylladb.com/csi.sock
        - --plugin-registration-path=/registration
        volumeMounts:
        - name: plugin-dir
          mountPath: /csi
        - name: registration-dir
          mountPath: /registration
      - name: liveness-probe
        image: registry.k8s.io/sig-storage/livenessprobe@sha256:cacee2b5c36dd59d4c7e8469c05c9e4ef53ecb2df9025fa8c10cdaf61bce62f0
        imagePullPolicy: IfNotPresent
        args:
        - --csi-address=/csi/csi.sock
        - --health-port=9809
        - --v=2
        volumeMounts:
        - name: plugin-dir
          mountPath: /csi
      volumes:
      - name: kubelet-dir
        hostPath:
          path: /var/lib/kubelet
          type: Directory
      - name: plugin-dir
        hostPath:
          path: /var/lib/kubelet/plugins/proxy.csi.scylladb.com/
          type: DirectoryOrCreate
      - name: state-dir
        hostPath:
          path: /var/lib/kubelet/plugins/proxy.csi.scylladb.com/state
          type: DirectoryOrCreate
      - name: registration-dir
        hostPath:
          path: /var/lib/kubelet/plugins_registry/
          type: Directory

