kind: Deployment
apiVersion: apps/v1
metadata:
  name: proxy-csi-driver-controller
  namespace: proxy-csi-driver
  labels:
    app.kubernetes.io/name: proxy-csi-driver-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: proxy-csi-driver-controller
  template:
    metadata:
      labels:
        app.kubernetes.io/name: proxy-csi-driver-controller
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      serviceAccountName: proxy-csi-driver-controller
      containers:
      - name: proxy-csi-driver-controller
        image: docker.io/rzetelskik/proxy-csi-driver:latest
        imagePullPolicy: Always
        args:
        - controller-server
        - --csi-address=/csi/csi.sock
        - --v=4
        volumeMounts:
        - name: plugin-dir
          mountPath: /csi
        ports:
        - name: healthz
          containerPort: 9809
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /healthz
            port: healthz
          initialDelaySeconds: 10
          timeoutSeconds: 3
          periodSeconds: 2
          failureThreshold: 5
      - name: liveness-probe
        image: registry.k8s.io/sig-storage/livenessprobe@sha256:cacee2b5c36dd59d4c7e8469c05c9e4ef53ecb2df9025fa8c10cdaf61bce62f0
        imagePullPolicy: IfNotPresent
        args:
        - --csi-address=/csi/csi.sock
        - --health-port=9809
        - --v=2
        volumeMounts:
        - name: plugin-dir
          mountPath: /csi
      - name: csi-provisioner
        image: registry.k8s.io/sig-storage/csi-provisioner@sha256:bf5a235b67d8aea00f5b8ec24d384a2480e1017d5458d8a63b361e9eeb1608a9
        imagePullPolicy: IfNotPresent
        args:
        - --v=5
        - --csi-address=/csi/csi.sock
        #        - --leader-election
        #        - --leader-election-namespace=$(NAMESPACE)
        #        - --controller-publish-readonly=true
        - --feature-gates=Topology=true
        - --immediate-topology=false
        - --volume-name-prefix=delayed-pvc
        volumeMounts:
        - name: plugin-dir
          mountPath: /csi
      - name: csi-attacher
        image: registry.k8s.io/sig-storage/csi-attacher@sha256:b4d611100ece2f9bc980d1cb19c2285b8868da261e3b1ee8f45448ab5512ab94
        imagePullPolicy: IfNotPresent
        args:
        - --v=5
        - --csi-address=/csi/csi.sock
        #        - --leader-election
        #        - --leader-election-namespace=$(NAMESPACE)
        - --timeout=120s
        volumeMounts:
        - name: plugin-dir
          mountPath: /csi
      volumes:
      - name: plugin-dir
        emptyDir: {}
